### ISSUE TITLE
URLResolver ImportError in models.py

### ISSUE THREAD

**Issue by jayden2** [mwesterhof/wagtail_app_pages#1]
* Wagtail App Pages version: 0.2.2
* Python version: (wagtail 2.1) (Django 1.11.13) (Python 3.6)
* Operating System: Ubuntu

### Description

Getting an import error:

File "/usr/local/lib/python3.4/dist-packages/wagtail_app_pages/models.py", line 1, in <module>
from django.urls import URLResolver
ImportError: cannot import name 'URLResolver'

### What I Did

added package to requirements.txt and installed package, during installation the setup errors out with the import error

**Comment by KyeRussell** [comment]
This is because `URLResolver` was only introduced in Django 2.0, whereas you are using Django 1.11.

If we are to make the application compatible with Django 1.11 we must determine how to accomplish what URLResolver is accomplishing in Django 2.0.

It looks largely undocumented so I am unable (at first glance) to determine a quick fix. Hopefully the author can shed some light on it.

**Comment by mwesterhof** [comment]
That's right. I don't officially support Django < 2.0 at this point. It seems I neglected to specify this in the requirements and the documentation. I did pin the wagtail version, so I guess I assumed that would be good enough.

In other news, I have been working on adding Django < 2.0 support in order to add it to a project that's stuck on an older version. I'll try to get it done today, and i'll release a new version if i'll manage this.

**Comment by KyeRussell** [comment]
Completely fair enough, Wagtail does make the assumption that Wagtail 2.0 is used with Django 2.0.

Keep in mind that Django 2.0 is not an LTS release and there may be plenty of people on Wagtail 2.0 + Django 1.11 if they're pinned to LTS Django releases (like me).

If you don't find the time to look into this I may be able to get around to it.

Thanks for the great application!

**Comment by mwesterhof** [comment]
@KyeRussell Yeah, no kidding... that's why I needed to fix the <2.0 support for another project ;)
I've been working on getting that support working though, and I just need to clean it up a bit and check if we're properly supporting both versions. I hope to be able to finish that today.

You're very welcome, by the way. I'm just glad to see that there's some interest in the project :)

**Comment by mwesterhof** [comment]
@jayden2  @KyeRussell 
I just released 0.2.3, introducing Django 1.11 support.
Thanks for reporting this issue, and please let me know if this fixes it, and if there are any more problems

Cheers

**Comment by jayden2** [comment]
@mwesterhof Thank you for your promptness, very much appreciated! :)

Works like a charm. Closing.

**Comment by KyeRussell** [comment]
Thanks mate.
